version: '3.8'

services:
  app-tracker:
    image: m-tracker:latest
    container_name: mtracker
    restart: always
    env_file: ./env
    ports:
      - "8080:8080"
    networks:
      - mtracker-network

networks:
  mtracker-network:
    external: true